replicaCount: 1
image:
  repository: kmaphosa/elk
  tag: logstash-8.9.2
  pullSecrets: [regcred]
service:
  type: ClusterIP
  port: 5044
env:
  ELASTICSEARCH_HOST: "elasticsearch"
  ELASTICSEARCH_USER: "elastic"
  ELASTICSEARCH_PASSWORD: "elastic123"
