apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <github_Repo>
    targetRevision: HEAD
    path: react-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
