apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kibana.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kibana.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kibana.name" . }}
    spec:
      containers:
      - name: kibana
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: "{{ .Values.env.ELASTICSEARCH_URL }}"
        - name: ELASTICSEARCH_USERNAME
          value: "{{ .Values.env.ELASTICSEARCH_USERNAME }}"
        - name: ELASTICSEARCH_PASSWORD
          value: "{{ .Values.env.ELASTICSEARCH_PASSWORD }}"
      imagePullSecrets:
      - name: {{ .Values.image.pullSecrets }}
