apiVersion: v1
kind: Service
metadata:
  name: {{ include "kibana.fullname" . }}
spec:
  selector:
    app: {{ include "kibana.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
