apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elasticsearch.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "elasticsearch.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "elasticsearch.name" . }}
    spec:
      containers:
      - name: elasticsearch
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: "single-node"
        - name: ELASTIC_PASSWORD
          value: "{{ .Values.env.ELASTIC_PASSWORD }}"
        - name: cluster.name
          value: "{{ .Values.env.clusterName }}"
        - name: bootstrap.memory_lock
          value: "{{ .Values.env.memoryLock }}"
        - name: ES_JAVA_OPTS
          value: "{{ .Values.env.javaOpts }}"
      imagePullSecrets:
      - name: {{ .Values.image.pullSecrets }}
      volumes:
      - name: esdata
        emptyDir: {}
