metricbeat.modules:
- module: kubernetes
  metricsets:
    - state_node
    - state_deployment
    - state_pod
    - state_service
  hosts: ["kube-state-metrics:8080"]
  period: 10s

- module: nginx
  metricsets:
    - stubstatus
  server_status_path: "nginx-status"
  hosts: ["http://nginx-ingress-controller:18080"]
  period: 10s

output.elasticsearch:
  hosts: ["<es_url>"]
  username: "elastic"
  password: "<password>"
  # If using Elasticsearch's default certificate
  ssl.ca_trusted_fingerprint: "<es cert fingerprint>"
setup.kibana:
  host: "<kibana_url>"