apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logstash.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "logstash.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "logstash.name" . }}
    spec:
      containers:
      - name: logstash
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5044
        env:
        - name: ELASTICSEARCH_HOST
          value: "{{ .Values.env.ELASTICSEARCH_HOST }}"
        - name: ELASTICSEARCH_USER
          value: "{{ .Values.env.ELASTICSEARCH_USER }}"
        - name: ELASTICSEARCH_PASSWORD
          value: "{{ .Values.env.ELASTICSEARCH_PASSWORD }}"
      imagePullSecrets:
      - name: {{ .Values.image.pullSecrets }}
