name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Nginx image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:latest ./Projects/k8-app-configs/nginx
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest

    - name: Build and push WordPress image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wordpress:latest ./Projects/k8-app-configs/wordpress
        docker push ${{ secrets.DOCKER_USERNAME }}/wordpress:latest

    - name: Deploy to Kubernetes
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.K8S_HOST }}
        username: ${{ secrets.K8S_USERNAME }}
        key: ${{ secrets.K8S_KEY }}
        script: |
          kubectl apply -f k8s/nginx-deployment.yaml
          kubectl apply -f k8s/wordpress-deployment.yaml
          kubectl apply -f k8s/mysql-deployment.yaml
          kubectl apply -f k8s/nginx-service.yaml
          kubectl apply -f k8s/wordpress-service.yaml
          kubectl apply -f k8s/mysql-service.yaml
